feat: logger or reply
project-mirai/chat-command pull request #8
Opened 2021-08-05 12:05 UTC by cssxsh

2021-08-07 21:44 UTC, Him188 requested changes

2021-08-07 21:44 UTC, Him188 commented on build.gradle.kts
> +version = "0.5.2"
有新功能，则应更新次版本号，即
```
version = "0.6.0"
```
不过 PR 也不应该修改版本号，因为不确定该 PR 会在哪个版本合并
```suggestion
version = "0.5.1"
```

2021-08-07 21:46 UTC, Him188 reviewed
应该考虑支持如下三种回复方案：
- 仅回复 user
- 仅回复 console
- 同时回复两者

现在方案新增的 true/false 设计将会导致未来无法增加上述功能支持。如果改为 enum 形式选择则可实现兼容：user/console/both 或其他更好的命名。

2021-08-08 03:04 UTC, Karlatemp requested changes

2021-08-08 03:04 UTC, Karlatemp commented on src/main/kotlin/PluginMain.kt
>              }
To verbose. Add config option to switch log or not

2021-08-08 03:04 UTC, Karlatemp commented on src/main/kotlin/PluginMain.kt
>                  )
Log exception to console ALWAYS

2021-08-08 03:04 UTC, Karlatemp commented on src/main/kotlin/PluginMain.kt
> +                    )
Logging to console is needless

2021-08-08 03:04 UTC, Karlatemp commented on src/main/kotlin/PluginMain.kt
>      )
PR shouldn't modify project version

2021-08-08 03:43 UTC, Karlatemp requested changes

2021-08-08 03:43 UTC, Karlatemp commented on src/main/kotlin/PluginMain.kt
> +            }
如果输出到 console, 无法根据 msg 判断是谁触发了该信息

2021-08-08 03:43 UTC, Karlatemp commented on src/main/kotlin/PluginMain.kt
>      override fun onEnable() {
Keep opt-in

2021-08-08 03:49 UTC, Him188 commented on src/main/kotlin/PluginMain.kt
>      override fun onEnable() {
上面有 @file:optin，也好

2023-02-09 11:07 UTC, Him188 approved these changes

2023-02-09 11:18 UTC, merged